// Services polyphemus knows how to connect, so adding one is picking it rather than finding its MCP
// server's address and working out how it signs in (roadmap: show and connect, 2). Each entry was
// checked against the service itself on the date it names; anything else is one "Other" away.

export interface ConnectionCatalogueEntry {
  id: string;
  name: string;
  /** One line: what an agent could do with it. */
  about: string;
  /** Its hosted MCP server; polyphemus's own servers (Google) have none. */
  url?: string;
  /**
   * oauth: sign in at the service, polyphemus registers itself. token: paste one the service gives you.
   * google: sign in with your own Google client, through polyphemus's own server for that service.
   * x: sign in with your own X app, through polyphemus's own X server.
   * plaid: your own Plaid app, and each bank linked on Plaid's own hosted page.
   */
  signIn: 'oauth' | 'token' | 'google' | 'x' | 'plaid' | 'none';
  google?: 'drive' | 'gmail';
  /** Built into polyphemus: it runs inside the daemon, with no server of its own. */
  builtin?: 'browser' | 'finance' | 'computer';
  /** For a token: how to make one that's no wider than it needs to be. */
  token?: { where: string; steps: string[]; placeholder: string };
  /** Where it's listed when you're picking one: productivity, developer, money… */
  category?: string;
  /** Brand colour for its tile. */
  color: string;
  /** When the entry was last checked against the service. */
  checked: string;
}

export const CONNECTION_CATALOGUE: readonly ConnectionCatalogueEntry[] = [
  {
    id: 'notion',
    name: 'Notion',
    about: 'Search, read and write pages and databases in your workspace.',
    url: 'https://mcp.notion.com/mcp',
    signIn: 'oauth',
    category: 'Docs & knowledge',
    color: '#191919',
    checked: '2026-09-12',
  },
  {
    id: 'github',
    name: 'GitHub',
    about: 'Repositories, issues, pull requests and CI, as your account.',
    url: 'https://api.githubcopilot.com/mcp/',
    // GitHub's MCP server signs in through github.com, which doesn't let apps register themselves,
    // so it takes a personal access token instead. A fine-grained one can be held to chosen repos.
    signIn: 'token',
    token: {
      where: 'https://github.com/settings/personal-access-tokens/new',
      steps: [
        'Open GitHub’s new fine-grained token page (the link below).',
        'Name it polyphemus, pick an expiry, and choose only the repositories agents should see.',
        'Under Repository permissions, give Read access to Contents, Issues, Pull requests and Metadata. Add Write only where you mean agents to change things.',
        'Generate it, copy it, and paste it here. It goes to your vault; polyphemus never shows it again.',
      ],
      placeholder: 'github_pat_…',
    },
    category: 'Developer',
    color: '#24292f',
    checked: '2026-09-12',
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    about: 'Search and read your Drive: Docs as text, Sheets as tables. Read-only.',
    signIn: 'google',
    google: 'drive',
    category: 'Files',
    color: '#1a73e8',
    checked: '2026-09-12',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    about: 'Search and read your mail. Read-only: nothing is sent.',
    signIn: 'google',
    google: 'gmail',
    category: 'Email & messages',
    color: '#c5221f',
    checked: '2026-09-12',
  },
  {
    id: 'x',
    name: 'X',
    about: 'Post, reply and delete posts as your account, and read your own posts and mentions. No DMs, follows or likes.',
    signIn: 'x',
    category: 'Websites & marketing',
    color: '#000000',
    checked: '2026-09-16',
  },
  {
    id: 'finance',
    name: 'Finance',
    about: 'Balances, transactions and spending from your banks, through Plaid or SimpleFIN. Read-only: nothing here can move money.',
    signIn: 'plaid',
    builtin: 'finance',
    category: 'Money',
    color: '#0f5132',
    checked: '2026-09-17',
  },
  // Checked 2026-09-18: each signs in the MCP way (it registers polyphemus itself), tested live.
  {
    id: 'linear',
    name: 'Linear',
    about: 'Issues, projects and cycles in your workspace.',
    url: 'https://mcp.linear.app/mcp',
    signIn: 'oauth',
    category: 'Projects & tasks',
    color: '#5E6AD2',
    checked: '2026-09-18',
  },
  {
    id: 'atlassian',
    name: 'Atlassian',
    about: 'Jira issues and Confluence pages.',
    url: 'https://mcp.atlassian.com/v2/mcp',
    signIn: 'oauth',
    category: 'Projects & tasks',
    color: '#0052CC',
    checked: '2026-09-18',
  },
  {
    id: 'asana',
    name: 'Asana',
    about: 'Tasks, projects and who’s doing what.',
    url: 'https://mcp.asana.com/sse',
    signIn: 'oauth',
    category: 'Projects & tasks',
    color: '#F06A6A',
    checked: '2026-09-18',
  },
  {
    id: 'monday',
    name: 'monday.com',
    about: 'Boards, items and updates.',
    url: 'https://mcp.monday.com/mcp',
    signIn: 'oauth',
    category: 'Projects & tasks',
    color: '#FF3D57',
    checked: '2026-09-18',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    about: 'Tasks, docs and spaces.',
    url: 'https://mcp.clickup.com/mcp',
    signIn: 'oauth',
    category: 'Projects & tasks',
    color: '#7B68EE',
    checked: '2026-09-18',
  },
  {
    id: 'todoist',
    name: 'Todoist',
    about: 'Your personal tasks and projects.',
    url: 'https://ai.todoist.net/mcp',
    signIn: 'oauth',
    category: 'Projects & tasks',
    color: '#E44332',
    checked: '2026-09-18',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    about: 'Bases, tables and records.',
    url: 'https://mcp.airtable.com/mcp',
    signIn: 'oauth',
    category: 'Docs & knowledge',
    color: '#18BFFF',
    checked: '2026-09-18',
  },
  {
    id: 'coda',
    name: 'Coda',
    about: 'Docs, tables and packs.',
    url: 'https://coda.io/apis/mcp',
    signIn: 'oauth',
    category: 'Docs & knowledge',
    color: '#EE5A29',
    checked: '2026-09-18',
  },
  {
    id: 'guru',
    name: 'Guru',
    about: 'Your company’s knowledge base.',
    url: 'https://mcp.api.getguru.com/mcp',
    signIn: 'oauth',
    category: 'Docs & knowledge',
    color: '#6554C0',
    checked: '2026-09-18',
  },
  {
    id: 'dovetail',
    name: 'Dovetail',
    about: 'User research, insights and highlights.',
    url: 'https://dovetail.com/api/mcp',
    signIn: 'oauth',
    category: 'Docs & knowledge',
    color: '#190041',
    checked: '2026-09-18',
  },
  {
    id: 'canva',
    name: 'Canva',
    about: 'Find, make and export designs.',
    url: 'https://mcp.canva.com/mcp',
    signIn: 'oauth',
    category: 'Design',
    color: '#00C4CC',
    checked: '2026-09-18',
  },
  {
    id: 'miro',
    name: 'Miro',
    about: 'Whiteboards, stickies and diagrams.',
    url: 'https://mcp.miro.com/',
    signIn: 'oauth',
    category: 'Design',
    color: '#FFD02F',
    checked: '2026-09-18',
  },
  {
    id: 'lucid',
    name: 'Lucid',
    about: 'Diagrams and flowcharts.',
    url: 'https://mcp.lucid.app/mcp',
    signIn: 'oauth',
    category: 'Design',
    color: '#F96B13',
    checked: '2026-09-18',
  },
  {
    id: 'gamma',
    name: 'Gamma',
    about: 'Generate decks, docs and web pages.',
    url: 'https://mcp.gamma.app/mcp',
    signIn: 'oauth',
    category: 'Design',
    color: '#6B38FB',
    checked: '2026-09-18',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    about: 'Files and folders in your Dropbox.',
    url: 'https://mcp.dropbox.com/mcp',
    signIn: 'oauth',
    category: 'Files',
    color: '#0061FF',
    checked: '2026-09-18',
  },
  {
    id: 'egnyte',
    name: 'Egnyte',
    about: 'Company files and folders.',
    url: 'https://mcp-server.egnyte.com/sse',
    signIn: 'oauth',
    category: 'Files',
    color: '#00968F',
    checked: '2026-09-18',
  },
  {
    id: 'calendly',
    name: 'Calendly',
    about: 'Event types, bookings and availability.',
    url: 'https://mcp.calendly.com/',
    signIn: 'oauth',
    category: 'Meetings & calendars',
    color: '#006BFF',
    checked: '2026-09-18',
  },
  {
    id: 'cal-com',
    name: 'Cal.com',
    about: 'Bookings and availability.',
    url: 'https://mcp.cal.com/mcp',
    signIn: 'oauth',
    category: 'Meetings & calendars',
    color: '#111827',
    checked: '2026-09-18',
  },
  {
    id: 'granola',
    name: 'Granola',
    about: 'Your meeting notes.',
    url: 'https://mcp.granola.ai/mcp',
    signIn: 'oauth',
    category: 'Meetings & calendars',
    color: '#3F6212',
    checked: '2026-09-18',
  },
  {
    id: 'fireflies',
    name: 'Fireflies',
    about: 'Meeting transcripts and summaries.',
    url: 'https://api.fireflies.ai/mcp',
    signIn: 'oauth',
    category: 'Meetings & calendars',
    color: '#8B5CF6',
    checked: '2026-09-18',
  },
  {
    id: 'otter',
    name: 'Otter',
    about: 'Meeting transcripts.',
    url: 'https://mcp.otter.ai/mcp',
    signIn: 'oauth',
    category: 'Meetings & calendars',
    color: '#1E6FFF',
    checked: '2026-09-18',
  },
  {
    id: 'tldv',
    name: 'tl;dv',
    about: 'Meeting recordings and notes.',
    url: 'https://mcp.tldv.io/mcp',
    signIn: 'oauth',
    category: 'Meetings & calendars',
    color: '#5B21B6',
    checked: '2026-09-18',
  },
  {
    id: 'jotform',
    name: 'Jotform',
    about: 'Forms and their submissions.',
    url: 'https://mcp.jotform.com/',
    signIn: 'oauth',
    category: 'Docs & knowledge',
    color: '#FF6100',
    checked: '2026-09-18',
  },
  {
    id: 'zapier',
    name: 'Zapier',
    about: 'Thousands of apps, through the actions you set up in Zapier.',
    url: 'https://mcp.zapier.com/api/mcp/mcp',
    signIn: 'oauth',
    category: 'Automation',
    color: '#FF4F00',
    checked: '2026-09-18',
  },
  {
    id: 'make',
    name: 'Make',
    about: 'Run and manage your Make scenarios.',
    url: 'https://mcp.make.com',
    signIn: 'oauth',
    category: 'Automation',
    color: '#6D00CC',
    checked: '2026-09-18',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    about: 'Repositories, merge requests and issues.',
    url: 'https://gitlab.com/api/v4/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#FC6D26',
    checked: '2026-09-18',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    about: 'Errors, issues and releases.',
    url: 'https://mcp.sentry.dev/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#362D59',
    checked: '2026-09-18',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    about: 'Projects, deployments and logs.',
    url: 'https://mcp.vercel.com',
    signIn: 'oauth',
    category: 'Developer',
    color: '#000000',
    checked: '2026-09-18',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    about: 'Sites, deploys and forms.',
    url: 'https://netlify-mcp.netlify.app/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#00AD9F',
    checked: '2026-09-18',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    about: 'Your whole Cloudflare account through its API.',
    url: 'https://mcp.cloudflare.com/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#F38020',
    checked: '2026-09-18',
  },
  {
    id: 'cloudflare-bindings',
    name: 'Cloudflare Workers',
    about: 'Workers, KV, R2 and D1.',
    url: 'https://bindings.mcp.cloudflare.com/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#F38020',
    checked: '2026-09-18',
  },
  {
    id: 'cloudflare-observability',
    name: 'Cloudflare Observability',
    about: 'Worker logs and analytics.',
    url: 'https://observability.mcp.cloudflare.com/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#F38020',
    checked: '2026-09-18',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    about: 'Postgres, auth and storage projects.',
    url: 'https://mcp.supabase.com/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#3ECF8E',
    checked: '2026-09-18',
  },
  {
    id: 'neon',
    name: 'Neon',
    about: 'Serverless Postgres databases and branches.',
    url: 'https://mcp.neon.tech/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#00E599',
    checked: '2026-09-18',
  },
  {
    id: 'prisma',
    name: 'Prisma Postgres',
    about: 'Prisma Postgres databases.',
    url: 'https://mcp.prisma.io/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#2D3748',
    checked: '2026-09-18',
  },
  {
    id: 'heroku',
    name: 'Heroku',
    about: 'Apps, dynos and add-ons.',
    url: 'https://mcp.heroku.com/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#430098',
    checked: '2026-09-18',
  },
  {
    id: 'railway',
    name: 'Railway',
    about: 'Deploy and manage services.',
    url: 'https://mcp.railway.com/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#0B0D0E',
    checked: '2026-09-18',
  },
  {
    id: 'circleci',
    name: 'CircleCI',
    about: 'Pipelines, builds and test results.',
    url: 'https://mcp.circleci.com/v1/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#343434',
    checked: '2026-09-18',
  },
  {
    id: 'buildkite',
    name: 'Buildkite',
    about: 'Pipelines and builds.',
    url: 'https://mcp.buildkite.com/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#14CC80',
    checked: '2026-09-18',
  },
  {
    id: 'postman',
    name: 'Postman',
    about: 'API collections, requests and environments.',
    url: 'https://mcp.postman.com/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#FF6C37',
    checked: '2026-09-18',
  },
  {
    id: 'huggingface-hub',
    name: 'Hugging Face Hub',
    about: 'Models, datasets and Spaces.',
    url: 'https://huggingface.co/mcp?login',
    signIn: 'oauth',
    category: 'Developer',
    color: '#FFD21E',
    checked: '2026-09-18',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    about: 'Run AI models in the cloud.',
    url: 'https://mcp.replicate.com/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#000000',
    checked: '2026-09-18',
  },
  {
    id: 'semgrep',
    name: 'Semgrep',
    about: 'Scan code for security problems.',
    url: 'https://mcp.semgrep.ai/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#1B2F3B',
    checked: '2026-09-18',
  },
  {
    id: 'socket',
    name: 'Socket',
    about: 'Is a package safe to install?',
    url: 'https://mcp.socket.dev/',
    signIn: 'oauth',
    category: 'Developer',
    color: '#C026D3',
    checked: '2026-09-18',
  },
  {
    id: 'jam',
    name: 'Jam',
    about: 'Bug reports with replays and logs.',
    url: 'https://mcp.jam.dev/mcp',
    signIn: 'oauth',
    category: 'Developer',
    color: '#7C3AED',
    checked: '2026-09-18',
  },
  {
    id: 'webflow',
    name: 'Webflow',
    about: 'Sites, pages and CMS content.',
    url: 'https://mcp.webflow.com/mcp',
    signIn: 'oauth',
    category: 'Websites & marketing',
    color: '#146EF5',
    checked: '2026-09-18',
  },
  {
    id: 'wix',
    name: 'Wix',
    about: 'Sites, stores and bookings.',
    url: 'https://mcp.wix.com/mcp',
    signIn: 'oauth',
    category: 'Websites & marketing',
    color: '#0C6EFC',
    checked: '2026-09-18',
  },
  {
    id: 'wordpress',
    name: 'WordPress.com',
    about: 'Sites, posts and pages.',
    url: 'https://public-api.wordpress.com/wpcom/v2/mcp/v1',
    signIn: 'oauth',
    category: 'Websites & marketing',
    color: '#3858E9',
    checked: '2026-09-18',
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary',
    about: 'Images and video in your media library.',
    url: 'https://asset-management.mcp.cloudinary.com/sse',
    signIn: 'oauth',
    category: 'Websites & marketing',
    color: '#3448C5',
    checked: '2026-09-18',
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    about: 'Email and SMS campaigns, lists and flows.',
    url: 'https://mcp.klaviyo.com/mcp',
    signIn: 'oauth',
    category: 'Websites & marketing',
    color: '#232426',
    checked: '2026-09-18',
  },
  {
    id: 'resend',
    name: 'Resend',
    about: 'Send email from your domain.',
    url: 'https://mcp.resend.com/mcp',
    signIn: 'oauth',
    category: 'Websites & marketing',
    color: '#000000',
    checked: '2026-09-18',
  },
  {
    id: 'bitly',
    name: 'Bitly',
    about: 'Short links and their clicks.',
    url: 'https://api-ssl.bitly.com/v4/mcp',
    signIn: 'oauth',
    category: 'Websites & marketing',
    color: '#EE6123',
    checked: '2026-09-18',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    about: 'Payments, customers, invoices and subscriptions.',
    url: 'https://mcp.stripe.com',
    signIn: 'oauth',
    category: 'Money',
    color: '#635BFF',
    checked: '2026-09-18',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    about: 'Payments, invoices and disputes.',
    url: 'https://mcp.paypal.com/mcp',
    signIn: 'oauth',
    category: 'Money',
    color: '#003087',
    checked: '2026-09-18',
  },
  {
    id: 'square',
    name: 'Square',
    about: 'Payments, orders and catalog.',
    url: 'https://mcp.squareup.com/sse',
    signIn: 'oauth',
    category: 'Money',
    color: '#000000',
    checked: '2026-09-18',
  },
  {
    id: 'ramp',
    name: 'Ramp',
    about: 'Company spend, cards and bills.',
    url: 'https://mcp.ramp.com/mcp',
    signIn: 'oauth',
    category: 'Money',
    color: '#E4F222',
    checked: '2026-09-18',
  },
  {
    id: 'mercury',
    name: 'Mercury',
    about: 'Business bank accounts and transactions.',
    url: 'https://mcp.mercury.com/mcp',
    signIn: 'oauth',
    category: 'Money',
    color: '#5266EB',
    checked: '2026-09-18',
  },
  {
    id: 'ibkr',
    name: 'Interactive Brokers',
    about: 'Your brokerage account, positions and orders.',
    url: 'https://api.ibkr.com/v1/api/mcp',
    signIn: 'oauth',
    category: 'Money',
    color: '#D81222',
    checked: '2026-09-18',
  },
  {
    id: 'webull',
    name: 'Webull',
    about: 'Your brokerage account and positions.',
    url: 'https://api.webull.com/mcp',
    signIn: 'oauth',
    category: 'Money',
    color: '#1A73E8',
    checked: '2026-09-18',
  },
  {
    id: 'attio',
    name: 'Attio',
    about: 'CRM records, lists and notes.',
    url: 'https://mcp.attio.com/mcp',
    signIn: 'oauth',
    category: 'Sales & support',
    color: '#111111',
    checked: '2026-09-18',
  },
  {
    id: 'close',
    name: 'Close',
    about: 'Leads, deals and calls in your CRM.',
    url: 'https://mcp.close.com/mcp',
    signIn: 'oauth',
    category: 'Sales & support',
    color: '#1463FF',
    checked: '2026-09-18',
  },
  {
    id: 'apollo',
    name: 'Apollo',
    about: 'Find people and companies to reach.',
    url: 'https://mcp.apollo.io/mcp',
    signIn: 'oauth',
    category: 'Sales & support',
    color: '#F6D32D',
    checked: '2026-09-18',
  },
  {
    id: 'zoominfo',
    name: 'ZoomInfo',
    about: 'Company and contact data.',
    url: 'https://mcp.zoominfo.com/mcp',
    signIn: 'oauth',
    category: 'Sales & support',
    color: '#E03C31',
    checked: '2026-09-18',
  },
  {
    id: 'gong',
    name: 'Gong',
    about: 'Sales calls and what was said.',
    url: 'https://mcp.gong.io/mcp',
    signIn: 'oauth',
    category: 'Sales & support',
    color: '#8039DF',
    checked: '2026-09-18',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    about: 'Customer conversations and contacts.',
    url: 'https://mcp.intercom.com/mcp',
    signIn: 'oauth',
    category: 'Sales & support',
    color: '#1F8DED',
    checked: '2026-09-18',
  },
  {
    id: 'helpscout',
    name: 'Help Scout',
    about: 'Your support inbox and customers.',
    url: 'https://mcp.helpscout.net/mcp',
    signIn: 'oauth',
    category: 'Sales & support',
    color: '#1292EE',
    checked: '2026-09-18',
  },
  {
    id: 'plain',
    name: 'Plain',
    about: 'Support threads and customers.',
    url: 'https://mcp.plain.com/mcp',
    signIn: 'oauth',
    category: 'Sales & support',
    color: '#111111',
    checked: '2026-09-18',
  },
  {
    id: 'pylon',
    name: 'Pylon',
    about: 'B2B support issues and accounts.',
    url: 'https://mcp.usepylon.com/',
    signIn: 'oauth',
    category: 'Sales & support',
    color: '#4F46E5',
    checked: '2026-09-18',
  },
  {
    id: 'posthog',
    name: 'PostHog',
    about: 'Product analytics, flags and session replays.',
    url: 'https://mcp.posthog.com/mcp',
    signIn: 'oauth',
    category: 'Data & analytics',
    color: '#F54E00',
    checked: '2026-09-18',
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    about: 'Product analytics and charts.',
    url: 'https://mcp.amplitude.com/mcp',
    signIn: 'oauth',
    category: 'Data & analytics',
    color: '#1E61F0',
    checked: '2026-09-18',
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    about: 'Product analytics and reports.',
    url: 'https://mcp.mixpanel.com/mcp',
    signIn: 'oauth',
    category: 'Data & analytics',
    color: '#7856FF',
    checked: '2026-09-18',
  },
  {
    id: 'hex',
    name: 'Hex',
    about: 'Data notebooks and apps.',
    url: 'https://app.hex.tech/mcp',
    signIn: 'oauth',
    category: 'Data & analytics',
    color: '#473982',
    checked: '2026-09-18',
  },
  {
    id: 'honeycomb',
    name: 'Honeycomb',
    about: 'Traces, queries and observability.',
    url: 'https://mcp.honeycomb.io/mcp',
    signIn: 'oauth',
    category: 'Data & analytics',
    color: '#FFB000',
    checked: '2026-09-18',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    about: 'Metrics, logs and monitors (US1 site).',
    url: 'https://mcp.datadoghq.com/api/unstable/mcp-server/mcp',
    signIn: 'oauth',
    category: 'Data & analytics',
    color: '#632CA6',
    checked: '2026-09-18',
  },
  {
    id: 'grafana',
    name: 'Grafana Cloud',
    about: 'Dashboards and queries.',
    url: 'https://mcp.grafana.com/mcp',
    signIn: 'oauth',
    category: 'Data & analytics',
    color: '#F46800',
    checked: '2026-09-18',
  },
  {
    id: 'axiom',
    name: 'Axiom',
    about: 'Logs and events.',
    url: 'https://mcp.axiom.co/mcp',
    signIn: 'oauth',
    category: 'Data & analytics',
    color: '#111111',
    checked: '2026-09-18',
  },
  {
    id: 'vanta',
    name: 'Vanta',
    about: 'Compliance controls and evidence.',
    url: 'https://mcp.vanta.com/mcp',
    signIn: 'oauth',
    category: 'Data & analytics',
    color: '#5A2EDC',
    checked: '2026-09-18',
  },
  {
    id: 'apify',
    name: 'Apify',
    about: 'Run scrapers and crawlers.',
    url: 'https://mcp.apify.com',
    signIn: 'oauth',
    category: 'Research & web',
    color: '#97D700',
    checked: '2026-09-18',
  },
  {
    id: 'tavily',
    name: 'Tavily',
    about: 'Web search made for agents.',
    url: 'https://mcp.tavily.com/mcp',
    signIn: 'oauth',
    category: 'Research & web',
    color: '#111827',
    checked: '2026-09-18',
  },
  {
    id: 'exa',
    name: 'Exa',
    about: 'Web search by meaning.',
    url: 'https://mcp.exa.ai/mcp',
    signIn: 'oauth',
    category: 'Research & web',
    color: '#1F40ED',
    checked: '2026-09-18',
  },
  {
    id: 'context7',
    name: 'Context7',
    about: 'Up-to-date docs for code libraries.',
    url: 'https://mcp.context7.com/mcp',
    signIn: 'oauth',
    category: 'Research & web',
    color: '#059669',
    checked: '2026-09-18',
  },
  {
    id: 'sp-global',
    name: 'S&P Global',
    about: 'Company financials and market data (needs their subscription).',
    url: 'https://kfinance.kensho.com/integrations/mcp',
    signIn: 'oauth',
    category: 'Research & web',
    color: '#D6002A',
    checked: '2026-09-18',
  },
  {
    id: 'morningstar',
    name: 'Morningstar',
    about: 'Fund and stock research (needs their subscription).',
    url: 'https://mcp.morningstar.com/mcp',
    signIn: 'oauth',
    category: 'Research & web',
    color: '#E3111C',
    checked: '2026-09-18',
  },
  {
    id: 'pitchbook',
    name: 'PitchBook',
    about: 'Private-market data (needs their subscription).',
    url: 'https://mcp.pitchbook.com/mcp',
    signIn: 'oauth',
    category: 'Research & web',
    color: '#0F1C2E',
    checked: '2026-09-18',
  },
  {
    id: 'meltwater',
    name: 'Meltwater',
    about: 'Media and social monitoring (needs their subscription).',
    url: 'https://api.meltwater.com/v2/mcp',
    signIn: 'oauth',
    category: 'Research & web',
    color: '#0C2340',
    checked: '2026-09-18',
  },
  // Open servers: no account, nothing to sign in to.
  {
    id: 'cloudflare-docs',
    name: 'Cloudflare Docs',
    about: 'Cloudflare’s documentation, searchable.',
    url: 'https://docs.mcp.cloudflare.com/mcp',
    signIn: 'none',
    category: 'Research & web',
    color: '#F38020',
    checked: '2026-09-18',
  },
  {
    id: 'microsoft-learn',
    name: 'Microsoft Learn',
    about: 'Microsoft’s documentation, searchable.',
    url: 'https://learn.microsoft.com/api/mcp',
    signIn: 'none',
    category: 'Research & web',
    color: '#0078D4',
    checked: '2026-09-18',
  },
  {
    id: 'deepwiki',
    name: 'DeepWiki',
    about: 'Ask about any public GitHub repository.',
    url: 'https://mcp.deepwiki.com/mcp',
    signIn: 'none',
    category: 'Research & web',
    color: '#111827',
    checked: '2026-09-18',
  },
  {
    id: 'excalidraw',
    name: 'Excalidraw',
    about: 'Sketch diagrams on a whiteboard.',
    url: 'https://mcp.excalidraw.com/mcp',
    signIn: 'none',
    category: 'Design',
    color: '#6965DB',
    checked: '2026-09-18',
  },
  {
    id: 'kiwi',
    name: 'Kiwi.com',
    about: 'Search flights.',
    url: 'https://mcp.kiwi.com',
    signIn: 'none',
    category: 'Travel & life',
    color: '#00A991',
    checked: '2026-09-18',
  },
  {
    id: 'instacart',
    name: 'Instacart',
    about: 'Recipes and shopping lists.',
    url: 'https://mcp.instacart.com/mcp',
    signIn: 'none',
    category: 'Travel & life',
    color: '#43B02A',
    checked: '2026-09-18',
  },
  {
    id: 'computer',
    name: 'Computer',
    about: 'Each agent’s own computer — a desktop with a browser, a terminal and files — that it can look at, click, type and run commands on. You watch or take over from the agent’s page.',
    signIn: 'none',
    builtin: 'computer',
    category: 'Research & web',
    color: '#334155',
    checked: '2026-09-18',
  },
  {
    id: 'browser',
    name: 'Browser',
    about: 'Open public web pages, read them, click and type: a fresh headless browser for each thread, signed in only where you kept a sign-in.',
    signIn: 'none',
    builtin: 'browser',
    category: 'Research & web',
    color: '#0f766e',
    checked: '2026-09-14',
  },
];

export const connectionCatalogueEntry = (id: string) => CONNECTION_CATALOGUE.find((entry) => entry.id === id);
