// Every command, declared once. The usage text, `poly help`, and `poly capabilities` are all
// generated from this list, so they can't drift apart (docs/design/cli-for-agents.md §1).

export interface CommandSpec {
  /** Stable id for agents and docs, e.g. "sessions.show". */
  id: string;
  usage: string;
  summary: string;
  /** read: changes nothing · write: changes polyphemus state · destructive: removes something · interactive: needs a person at a terminal */
  effects: 'read' | 'write' | 'destructive' | 'interactive';
  /** Prints the JSON envelope with --json, or when stdout isn't a terminal. */
  json: boolean;
  examples: string[];
  /** Arguments, in order (positional unless `flag`): these become the MCP tool's input schema. */
  params?: Array<{ name: string; type: 'string' | 'number'; description: string; required?: boolean; flag?: string }>;
}

export const COMMANDS: readonly CommandSpec[] = [
  {
    id: 'session',
    usage: 'poly',
    summary: 'start a new session (it runs in the daemon when that’s up, so your phone sees it too)',
    effects: 'interactive',
    json: false,
    examples: ['poly', 'poly -m codex'],
  },
  {
    id: 'session.local',
    usage: 'poly --local',
    summary: 'run the session in this terminal instead of the daemon (your phone won’t see it)',
    effects: 'interactive',
    json: false,
    examples: ['poly --local'],
  },
  { id: 'session.continue', usage: 'poly -c', summary: 'continue the latest session in this folder', effects: 'interactive', json: false, examples: ['poly -c'] },
  { id: 'session.resume', usage: 'poly -r <id>', summary: 'resume a session by id (or id prefix)', effects: 'interactive', json: false, examples: ['poly -r 3cdf'] },
  {
    id: 'session.model',
    usage: 'poly -m <model>',
    summary: 'use a model: an alias (codex), a provider (grok-build), or provider:model-id',
    effects: 'interactive',
    json: false,
    examples: ['poly -m claude', 'poly -m anthropic:claude-opus-5'],
  },
  {
    id: 'prompt',
    usage: 'poly -p "<prompt>" [-y]',
    summary: 'run one prompt, print the reply, and exit (-y lets it run tools)',
    effects: 'write',
    json: false,
    examples: ['poly -p "summarize README.md"', 'poly -p "fix the failing test" -y'],
  },
  { id: 'yolo', usage: 'poly -y, --yolo', summary: 'run every tool without asking (trusted folders only)', effects: 'interactive', json: false, examples: ['poly --yolo'] },
  {
    id: 'capabilities',
    usage: 'poly capabilities',
    summary: 'what polyphemus can do, as JSON: commands, models, projects, paths. Agents: start here',
    effects: 'read',
    json: true,
    examples: ['poly capabilities --json'],
  },
  {
    id: 'loop',
    usage: 'poly loop <goal…> --until <command> [--max N] [-a agent] [-y]',
    summary: 'work toward a goal a round at a time, in fresh sessions, until the command passes (runs in the daemon)',
    effects: 'write',
    json: true,
    examples: ['poly loop "make the e2e suite pass" --until "pnpm e2e" --max 10', 'poly loop "fix the flaky login test" --until "pnpm test login" -a builder -y'],
    params: [
      { name: 'goal', type: 'string', description: 'What it’s working toward', required: true },
      { name: 'until', type: 'string', description: 'A command that exits 0 when the goal is met', required: true, flag: 'until' },
      { name: 'max', type: 'number', description: 'The most rounds (default 5)', flag: 'max' },
    ],
  },
  {
    id: 'update',
    usage: 'poly update [--check] [--channel stable|beta] [--now]',
    summary: 'install the newest polyphemus beside this one, check it against a copy of your data, back the data up, and switch; if the service doesn’t come up, the old version and the data go back on their own. --check only says whether there is one; --channel switches between stable releases and betas; --now doesn’t wait for running sessions',
    effects: 'write',
    json: true,
    examples: ['poly update --check', 'poly update', 'poly update --channel beta'],
  },
  {
    id: 'rollback',
    usage: 'poly rollback [--restore] [--now]',
    summary: 'go back to the version before the last update, keeping your data; --restore also puts back the data from just before that update (losing what happened since)',
    effects: 'write',
    json: false,
    examples: ['poly rollback', 'poly rollback --restore'],
  },
  {
    id: 'self-check',
    usage: 'poly self-check',
    summary: 'check that this version works with this computer’s data, on a copy of it: changes nothing',
    effects: 'read',
    json: true,
    examples: ['poly self-check', 'poly self-check --json'],
  },
  {
    id: 'intake',
    usage: 'poly intake <text…> [--kind feedback|idea|finding]',
    summary: 'add feedback, an idea or a finding to this folder’s project: it waits on Home until someone makes work of it (runs in the daemon)',
    effects: 'write',
    json: true,
    examples: ['poly intake "Exports drop rows with commas in them" --kind finding', 'cat feedback.txt | xargs -0 poly intake --kind feedback'],
    params: [
      { name: 'text', type: 'string', description: 'What came in', required: true },
      { name: 'kind', type: 'string', description: 'feedback (default), idea or finding', flag: 'kind' },
    ],
  },
  { id: 'help', usage: 'poly help [command]', summary: 'this list, or one command in detail', effects: 'read', json: true, examples: ['poly help', 'poly help sessions show --json'] },
  {
    id: 'models',
    usage: 'poly models [--all]',
    summary: 'every model, and whether it’s ready to use; --all asks each provider what it offers',
    effects: 'read',
    json: true,
    examples: ['poly models --json', 'poly models --all'],
  },
  {
    id: 'models.add',
    usage: 'poly models add <name> <provider>:<model-id> [--effort <level>]',
    summary: 'give a model a name you can use with -m (any provider, including your own server)',
    effects: 'write',
    json: true,
    examples: ['poly models add llama ollama:llama3.1', 'poly models add r1 openrouter:deepseek/deepseek-r1 --effort high'],
  },
  { id: 'models.rm', usage: 'poly models rm <name>', summary: 'forget a named model (the provider stays)', effects: 'write', json: true, examples: ['poly models rm llama'] },
  {
    id: 'usage',
    usage: 'poly usage',
    summary: 'how much of each plan is used, and whether it will last until it resets',
    effects: 'read',
    json: true,
    examples: ['poly usage', 'poly usage --json'],
  },
  { id: 'sessions', usage: 'poly sessions [--archived]', summary: 'recent sessions (archived ones only with --archived)', effects: 'read', json: true, examples: ['poly sessions --json', 'poly sessions --archived'] },
  {
    id: 'sessions.search',
    usage: 'poly sessions search <words…>',
    summary: 'sessions whose title or conversation contains the words, archived ones included',
    effects: 'read',
    json: true,
    examples: ['poly sessions search flaky test', 'poly sessions search "release notes" --json'],
    params: [{ name: 'words', type: 'string', description: 'What to look for in titles and in what was said', required: true }],
  },
  { id: 'sessions.rename', usage: 'poly sessions rename <id> <title…>', summary: 'give a session a better name', effects: 'write', json: true, examples: ['poly sessions rename 3cdf "Flaky login test"'] },
  {
    id: 'sessions.archive',
    usage: 'poly sessions archive | unarchive <id>',
    summary: 'take a session off the lists without deleting it (sending it a message brings it back)',
    effects: 'write',
    json: true,
    examples: ['poly sessions archive 3cdf', 'poly sessions unarchive 3cdf'],
  },
  { id: 'sessions.delete', usage: 'poly sessions delete <id>', summary: 'delete a session and its conversation for good', effects: 'destructive', json: true, examples: ['poly sessions delete 3cdf'] },
  {
    id: 'sessions.show',
    usage: 'poly sessions show <id> [--last <n>]',
    summary: 'a session’s conversation: messages, tool calls, and results',
    effects: 'read',
    json: true,
    examples: ['poly sessions show 3cdf80b3', 'poly sessions show 3cdf --last 6 --json'],
    params: [
      { name: 'id', type: 'string', description: 'The session id, or the start of it', required: true },
      { name: 'last', type: 'number', description: 'Only the most recent N messages', flag: '--last' },
    ],
  },
  { id: 'login', usage: 'poly login <provider>', summary: 'save an API key for a provider', effects: 'interactive', json: false, examples: ['poly login anthropic'] },
  {
    id: 'agents',
    usage: 'poly agents',
    summary: 'agents you can work with: your library, plus this project’s',
    effects: 'read',
    json: true,
    examples: ['poly agents', 'poly agents --json'],
  },
  {
    id: 'agents.new',
    usage: 'poly agents new <name> [what it’s for…] [--from <template>] [--model <model>] [--mark <shape/colour>] [--project] [--blank]',
    summary: 'make an agent: its own model route, persona, instructions, and skills',
    effects: 'write',
    json: true,
    examples: ['poly agents new bd "chasing the pipeline and keeping the CRM honest"', 'poly agents new reviewer --from reviewer', 'poly agents new ops "keeping the servers happy" --model codex --mark hex/amber --project'],
  },
  {
    id: 'agents.templates',
    usage: 'poly agents templates',
    summary: 'agents that come with polyphemus, to make your own from',
    effects: 'read',
    json: true,
    examples: ['poly agents templates'],
  },
  {
    id: 'agents.edit',
    usage: 'poly agents edit <name> [--title …] [--description …] [--model …] [--fallback a,b] [--mark shape/colour] [--persona file|-] [--instructions file|-] [--dry-run]',
    summary: 'change an agent: only what you name, each value checked (a model must be on your list); never edit its files by hand',
    effects: 'write',
    json: true,
    examples: ['poly agents edit scout --model claude-code:claude-opus-5 --fallback grok-build:grok-4.6', 'poly agents edit bd --description "chasing the pipeline"', 'cat persona.md | poly agents edit bd --persona -'],
    params: [{ name: 'name', type: 'string', description: 'The agent’s name', required: true }],
  },
  {
    id: 'agents.show',
    usage: 'poly agents show <name>',
    summary: 'an agent’s settings, persona, and instructions',
    effects: 'read',
    json: true,
    examples: ['poly agents show reviewer'],
    params: [{ name: 'name', type: 'string', description: 'The agent’s name', required: true }],
  },
  {
    id: 'skills',
    usage: 'poly skills [--agent <agent>]',
    summary: 'skills sessions here can use: your library, this project’s, and with --agent that agent’s own',
    effects: 'read',
    json: true,
    examples: ['poly skills', 'poly skills --agent scout --json'],
  },
  {
    id: 'skills.new',
    usage: 'poly skills new <name> [description…] [--from <template>] [--project | --agent <agent>]',
    summary: 'start a skill: a SKILL.md a model opens when the work matches; --agent makes it that agent’s own, going wherever it goes',
    effects: 'write',
    json: true,
    examples: ['poly skills new review-pr --from review-pr', 'poly skills new deploy "shipping this project" --project', 'poly skills new debt-snowball "ordering debts smallest first" --agent scout'],
  },
  {
    id: 'skills.browse',
    usage: 'poly skills browse [words…]',
    summary: 'the open skill library — Anthropic, OpenAI, GitHub, Microsoft, Hugging Face and more — searched by what you type',
    effects: 'read',
    json: true,
    examples: ['poly skills browse pdf forms', 'poly skills browse --json'],
  },
  {
    id: 'skills.install',
    usage: 'poly skills install <source/name> [--agent <agent> | --project] [--replace]',
    summary: 'add a skill from the library: shared by every agent, one agent’s own (--agent), or a project’s; its licence goes with it',
    effects: 'write',
    json: true,
    examples: ['poly skills install superpowers/brainstorming', 'poly skills install anthropic/frontend-design --agent le-artist'],
  },
  {
    id: 'skills.templates',
    usage: 'poly skills templates',
    summary: 'skills that come with polyphemus, to make your own from',
    effects: 'read',
    json: true,
    examples: ['poly skills templates'],
  },
  {
    id: 'skills.show',
    usage: 'poly skills show <name>',
    summary: 'a skill’s instructions, as a model reads them',
    effects: 'read',
    json: true,
    examples: ['poly skills show review-pr'],
    params: [{ name: 'name', type: 'string', description: 'The skill’s name', required: true }],
  },
  { id: 'projects', usage: 'poly projects', summary: 'your projects, and any that need setup or review', effects: 'read', json: true, examples: ['poly projects --json'] },
  {
    id: 'projects.new',
    usage: 'poly projects new <name> [--about "…"] [--from <git-url>] [--git]',
    summary: 'start a project in ~/projects (or clone one), set up for agents',
    effects: 'write',
    json: true,
    examples: ['poly projects new "Side Quest" --about "A tiny arcade game" --git', 'poly projects new site --from https://github.com/you/site', 'poly projects new "Acme Finance" --about "Month-end close and the reports it feeds"'],
  },
  {
    id: 'projects.add',
    usage: 'poly projects add [folder] [--name <name>] [--about "…"]',
    summary: 'add a folder you already have (default: this one)',
    effects: 'write',
    json: true,
    examples: ['poly projects add', 'poly projects add ~/code/thing --name Thing'],
  },
  {
    id: 'projects.rename',
    usage: 'poly projects rename <project> <name…>',
    summary: 'change the name people see (the address and the folder stay)',
    effects: 'write',
    json: true,
    examples: ['poly projects rename side-quest "Night Game"'],
  },
  {
    id: 'projects.move',
    usage: 'poly projects move <project> <folder>',
    summary: 'a project’s files moved: point polyphemus at the new folder (past sessions follow)',
    effects: 'write',
    json: true,
    examples: ['poly projects move polyphemus ~/code/polyphemus'],
  },
  {
    id: 'projects.orient',
    usage: 'poly projects orient [project] [-m <model>]',
    summary: 'an agent reads what’s in the folder and drafts AGENTS.md and notes for review',
    effects: 'interactive',
    json: false,
    examples: ['poly projects orient polyphemus'],
  },
  { id: 'projects.review', usage: 'poly projects review [project]', summary: 'keep or discard what agents proposed', effects: 'interactive', json: false, examples: ['poly projects review polyphemus'] },
  {
    id: 'projects.status',
    usage: 'poly projects park | archive | activate <project>',
    summary: 'hide a project without deleting anything, or bring it back',
    effects: 'write',
    json: true,
    examples: ['poly projects park side-quest'],
  },
  {
    id: 'projects.share',
    usage: 'poly projects share | unshare <project> <person> [--role member|viewer]',
    summary: 'give someone a role in one project (member works and approves; viewer reads), or take it away',
    effects: 'write',
    json: true,
    examples: ['poly projects share game-night sam', 'poly projects share polyphemus sam --role viewer', 'poly projects unshare polyphemus sam'],
  },
  { id: 'routine', usage: 'poly routine', summary: 'your routines: schedule, next run, and last result', effects: 'read', json: true, examples: ['poly routine', 'poly routine --json'] },
  {
    id: 'routine.show',
    usage: 'poly routine show <name>',
    summary: 'a routine’s settings and its last 20 firings, including why any were skipped',
    effects: 'read',
    json: true,
    examples: ['poly routine show morning-brief'],
    params: [{ name: 'name', type: 'string', description: 'The routine’s name or full id (project/name)', required: true }],
  },
  {
    id: 'routine.next',
    usage: 'poly routine next <name> [--count <n>]',
    summary: 'the next times it will run',
    effects: 'read',
    json: true,
    examples: ['poly routine next morning-brief --count 3'],
    params: [
      { name: 'name', type: 'string', description: 'The routine’s name or full id', required: true },
      { name: 'count', type: 'number', description: 'How many times to list (default 5)', flag: '--count' },
    ],
  },
  { id: 'routine.run', usage: 'poly routine run <name>', summary: 'run it now, through the daemon and its usual checks', effects: 'write', json: true, examples: ['poly routine run morning-brief'] },
  { id: 'routine.accept', usage: 'poly routine accept <name> --digest <digest>', summary: 'let a project’s new or changed routine run, exactly as the version poly routine show printed', effects: 'write', json: true, examples: ['poly routine show morning-brief', 'poly routine accept morning-brief --digest 3f2a…'] },
  { id: 'routine.pause', usage: 'poly routine pause | resume <name>', summary: 'stop its schedule, or start it again', effects: 'write', json: true, examples: ['poly routine pause morning-brief'] },
  { id: 'routine.check', usage: 'poly routine check', summary: 'find mistakes in routine files (exit 2 if any)', effects: 'read', json: true, examples: ['poly routine check'] },
  {
    id: 'config.get',
    usage: 'poly config get [key]',
    summary: 'a setting’s value (dotted, like routing.fallback), or every setting',
    effects: 'read',
    json: true,
    examples: ['poly config get routing', 'poly config get default_model --json'],
    params: [{ name: 'key', type: 'string', description: 'A dotted setting, like routing.fallback; leave out for all' }],
  },
  {
    id: 'config.set',
    usage: 'poly config set <key> <value> [--dry-run]',
    summary: 'change a setting: validated first, saved as a revision you can undo',
    effects: 'write',
    json: true,
    examples: ['poly config set routing.on_fallback continue', 'poly config set routing.fallback \'["codex", "claude-api"]\' --dry-run'],
  },
  { id: 'config.unset', usage: 'poly config unset <key> [--dry-run]', summary: 'remove a setting (validated and recorded the same way)', effects: 'write', json: true, examples: ['poly config unset models.claude.fallback'] },
  { id: 'config.validate', usage: 'poly config validate', summary: 'check config.toml, and whether it was edited outside polyphemus', effects: 'read', json: true, examples: ['poly config validate'] },
  {
    id: 'config.diff',
    usage: 'poly config diff [revision]',
    summary: 'what changed in config.toml since a revision (default: the last recorded one)',
    effects: 'read',
    json: true,
    examples: ['poly config diff', 'poly config diff 3'],
    params: [{ name: 'revision', type: 'number', description: 'A revision number; leave out for the last recorded one' }],
  },
  { id: 'config.history', usage: 'poly config history', summary: 'every recorded change: when, what, and who', effects: 'read', json: true, examples: ['poly config history'] },
  {
    id: 'config.undo',
    usage: 'poly config undo | rollback <revision>',
    summary: 'go back one change, or to a revision (itself recorded, so it can be undone too)',
    effects: 'write',
    json: true,
    examples: ['poly config undo', 'poly config rollback 3'],
  },
  { id: 'config.adopt', usage: 'poly config adopt', summary: 'keep an edit made to config.toml outside polyphemus (after checking it)', effects: 'write', json: true, examples: ['poly config adopt'] },
  {
    id: 'secrets.ls',
    usage: 'poly secrets ls',
    summary: 'what’s in the vault: names, kinds, and notes (never values)',
    effects: 'read',
    json: true,
    examples: ['poly secrets ls'],
  },
  {
    id: 'secrets.set',
    usage: 'poly secrets set <name> [--kind api-key|token|password|other] [--note "…"]',
    summary: 'put a secret in the vault (typed hidden, or piped in)',
    effects: 'write',
    json: true,
    examples: ['poly secrets set aws/acme-prod --note "Acme deploy"', 'cat key.txt | poly secrets set provider/anthropic --kind api-key'],
  },
  { id: 'secrets.rm', usage: 'poly secrets rm <name>', summary: 'remove a secret from the vault', effects: 'destructive', json: true, examples: ['poly secrets rm aws/acme-prod'] },
  {
    id: 'secrets.show',
    usage: 'poly secrets show <name> --reveal',
    summary: 'print one secret, on a terminal only (never into a pipe or a file)',
    effects: 'read',
    json: false,
    examples: ['poly secrets show aws/acme-prod --reveal'],
  },
  { id: 'secrets.migrate', usage: 'poly secrets migrate', summary: 'move plain-text keys from credentials.json into the vault', effects: 'write', json: true, examples: ['poly secrets migrate'] },
  {
    id: 'secrets.audit',
    usage: 'poly secrets audit [--last <n>]',
    summary: 'which secret was used, by whom, and when (never values)',
    effects: 'read',
    json: true,
    examples: ['poly secrets audit --last 50'],
    params: [{ name: 'last', type: 'number', description: 'How many entries (default 30)', flag: '--last' }],
  },
  {
    id: 'secrets.doctor',
    usage: 'poly secrets doctor [--machine]',
    summary: 'checks polyphemus’s own secrets; --machine also checks this computer for credentials a bot could inherit',
    effects: 'read',
    json: true,
    examples: ['poly secrets doctor', 'poly secrets doctor --machine'],
  },
  {
    id: 'mcp.serve',
    usage: 'poly mcp serve',
    summary: 'Polyphemus’s read-only commands as MCP tools (add to Claude Code: claude mcp add polyphemus -- poly mcp serve)',
    effects: 'interactive',
    json: false,
    examples: ['claude mcp add polyphemus -- poly mcp serve'],
  },
  {
    id: 'serve',
    usage: 'poly serve',
    summary: 'run the daemon in this terminal, so your phone can reach your sessions (over Tailscale)',
    effects: 'interactive',
    json: false,
    examples: ['poly serve'],
  },
  {
    id: 'service.install',
    usage: 'poly service install',
    summary: 'keep the daemon running in the background, started at boot, on its own copy',
    effects: 'write',
    json: false,
    examples: ['poly service install'],
  },
  {
    id: 'service.update',
    usage: 'poly service update [--now]',
    summary: 'deploy your latest commit to it once its tests pass; with sessions working, it goes live when they finish, and goes back if it doesn’t come up',
    effects: 'write',
    json: false,
    examples: ['poly service update'],
  },
  {
    id: 'service.rollback',
    usage: 'poly service rollback',
    summary: 'go back to the copy that was live before this one',
    effects: 'write',
    json: false,
    examples: ['poly service rollback'],
  },
  {
    id: 'service.manage',
    usage: 'poly service status | logs | restart | uninstall',
    summary: 'check on, restart, or remove the background service',
    effects: 'write',
    json: false,
    examples: ['poly service status'],
  },
  { id: 'doctor', usage: 'poly doctor', summary: 'what this computer has and lacks for polyphemus — models, containers, Tailscale, a browser — and what to do about each; exits 1 if something stops it working', effects: 'read', json: true, examples: ['poly doctor', 'poly doctor --json'] },
  { id: 'start', usage: 'poly start', summary: 'open polyphemus on this computer: the daemon in the background, this computer paired, and the setup wizard in your browser', effects: 'write', json: false, examples: ['poly start'] },
  { id: 'pair', usage: 'poly pair [--person <person>]', summary: 'a one-time code (and QR code) that pairs a phone with the daemon, as you or as someone you added', effects: 'write', json: false, examples: ['poly pair', 'poly pair --person sam'] },
  { id: 'people', usage: 'poly people', summary: 'who uses this install: you, and anyone with a role in a project', effects: 'read', json: true, examples: ['poly people', 'poly people --json'] },
  { id: 'people.add', usage: 'poly people add <name>', summary: 'add someone; they see nothing until they belong to a project', effects: 'write', json: true, examples: ['poly people add Sam'] },
  { id: 'people.rename', usage: 'poly people rename <person> <name>', summary: 'change the name other people see on what someone did', effects: 'write', json: true, examples: ['poly people rename you Alex'] },
  { id: 'people.remove', usage: 'poly people remove <person>', summary: 'remove someone: their devices stop working, what they did stays attributed', effects: 'destructive', json: true, examples: ['poly people remove sam'] },
  { id: 'devices', usage: 'poly devices', summary: 'paired devices', effects: 'read', json: true, examples: ['poly devices --json'] },
  { id: 'devices.revoke', usage: 'poly devices revoke <id>', summary: 'cut a device off', effects: 'destructive', json: true, examples: ['poly devices revoke 0da63962'] },
];

/** The usage text for `polyphemus --help` and `poly help`. */
export function usageText(): string {
  const lines = COMMANDS.map(({ usage, summary }) => (usage.length <= 26 ? `  ${usage.padEnd(27)} ${summary}` : `  ${usage}\n  ${' '.repeat(28)}${summary}`));
  return `Usage:\n${lines.join('\n')}\n\nAgents and scripts: every list and show command prints JSON with --json (or when piped). Start with: poly capabilities`;
}

/** A command by id ("sessions.show") or words ("sessions show"). */
export function findCommand(name: string): CommandSpec | undefined {
  const id = name.trim().replace(/\s+/g, '.');
  return COMMANDS.find((command) => command.id === id);
}
